### ISSUE TITLE
Build fail on master

### ISSUE THREAD

**Issue by mixonic** [rwjblue/ember-debug-handlers-polyfill#4]
Builds fail on master of this repo. The codebase pre-dates lockfiles, so there is no `yarn.lock` or `package-lock.json` to pin library versions. Evidently something has drifted.

In general, we should be able to upgrade this addon's version of Ember-CLI and commit the update with a lockfile.

Refs: https://github.com/rwjblue/ember-debug-handlers-polyfill/pull/3

**Comment by backspace** [comment]
Since caching is set up on Travis, maybe getting the `node_modules` from a cache would help determine working versions? If this seems worth looking into, let me know.
